# Generated by Django 3.1.5 on 2021-01-20 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('54a7421d-0220-49cb-9258-8f14ab6df598'), editable=False, primary_key=True, serialize=False),
        ),
    ]
