# Generated by Django 3.1.5 on 2021-01-20 06:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210120_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('89a09d0f-0db0-4a19-a3f8-572fa00ddb2c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
