# Generated by Django 3.1.5 on 2021-01-20 06:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210120_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fa468fa3-39b9-4c60-b2ca-9e30ca81bce5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
